version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
